// flow-typed signature: fe4ebba1c3ae824af76f4b7f53af9fa2
// flow-typed version: <<STUB>>/@types/react_v^16.4.18/flow_v0.83.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@types/react'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@types/react' {
  declare module.exports: any;
}
