// flow-typed signature: cbeb73616bb3ace409a5bf881836d4db
// flow-typed version: <<STUB>>/@emotion/is-prop-valid_v^0.7.3/flow_v0.93.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@emotion/is-prop-valid'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@emotion/is-prop-valid' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@emotion/is-prop-valid/dist/is-prop-valid.browser.cjs' {
  declare module.exports: any;
}

declare module '@emotion/is-prop-valid/dist/is-prop-valid.browser.esm' {
  declare module.exports: any;
}

declare module '@emotion/is-prop-valid/dist/is-prop-valid.cjs.dev' {
  declare module.exports: any;
}

declare module '@emotion/is-prop-valid/dist/is-prop-valid.cjs' {
  declare module.exports: any;
}

declare module '@emotion/is-prop-valid/dist/is-prop-valid.cjs.prod' {
  declare module.exports: any;
}

declare module '@emotion/is-prop-valid/dist/is-prop-valid.esm' {
  declare module.exports: any;
}

declare module '@emotion/is-prop-valid/src/index' {
  declare module.exports: any;
}

declare module '@emotion/is-prop-valid/src/props' {
  declare module.exports: any;
}

// Filename aliases
declare module '@emotion/is-prop-valid/dist/is-prop-valid.browser.cjs.js' {
  declare module.exports: $Exports<'@emotion/is-prop-valid/dist/is-prop-valid.browser.cjs'>;
}
declare module '@emotion/is-prop-valid/dist/is-prop-valid.browser.esm.js' {
  declare module.exports: $Exports<'@emotion/is-prop-valid/dist/is-prop-valid.browser.esm'>;
}
declare module '@emotion/is-prop-valid/dist/is-prop-valid.cjs.dev.js' {
  declare module.exports: $Exports<'@emotion/is-prop-valid/dist/is-prop-valid.cjs.dev'>;
}
declare module '@emotion/is-prop-valid/dist/is-prop-valid.cjs.js' {
  declare module.exports: $Exports<'@emotion/is-prop-valid/dist/is-prop-valid.cjs'>;
}
declare module '@emotion/is-prop-valid/dist/is-prop-valid.cjs.prod.js' {
  declare module.exports: $Exports<'@emotion/is-prop-valid/dist/is-prop-valid.cjs.prod'>;
}
declare module '@emotion/is-prop-valid/dist/is-prop-valid.esm.js' {
  declare module.exports: $Exports<'@emotion/is-prop-valid/dist/is-prop-valid.esm'>;
}
declare module '@emotion/is-prop-valid/src/index.js' {
  declare module.exports: $Exports<'@emotion/is-prop-valid/src/index'>;
}
declare module '@emotion/is-prop-valid/src/props.js' {
  declare module.exports: $Exports<'@emotion/is-prop-valid/src/props'>;
}
