// flow-typed signature: b0c23c1c6141784e1f4510c7bd91ee59
// flow-typed version: <<STUB>>/all-contributors-cli_v^5.4.1/flow_v0.83.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'all-contributors-cli'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'all-contributors-cli' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'all-contributors-cli/dist/cli' {
  declare module.exports: any;
}

declare module 'all-contributors-cli/dist/contributors/add' {
  declare module.exports: any;
}

declare module 'all-contributors-cli/dist/contributors/index' {
  declare module.exports: any;
}

declare module 'all-contributors-cli/dist/contributors/prompt' {
  declare module.exports: any;
}

declare module 'all-contributors-cli/dist/generate/format-badge' {
  declare module.exports: any;
}

declare module 'all-contributors-cli/dist/generate/format-contribution-type' {
  declare module.exports: any;
}

declare module 'all-contributors-cli/dist/generate/format-contributor' {
  declare module.exports: any;
}

declare module 'all-contributors-cli/dist/generate/index' {
  declare module.exports: any;
}

declare module 'all-contributors-cli/dist/init/index' {
  declare module.exports: any;
}

declare module 'all-contributors-cli/dist/init/init-content' {
  declare module.exports: any;
}

declare module 'all-contributors-cli/dist/init/prompt' {
  declare module.exports: any;
}

declare module 'all-contributors-cli/dist/repo/github' {
  declare module.exports: any;
}

declare module 'all-contributors-cli/dist/repo/gitlab' {
  declare module.exports: any;
}

declare module 'all-contributors-cli/dist/repo/index' {
  declare module.exports: any;
}

declare module 'all-contributors-cli/dist/util/config-file' {
  declare module.exports: any;
}

declare module 'all-contributors-cli/dist/util/contribution-types' {
  declare module.exports: any;
}

declare module 'all-contributors-cli/dist/util/git' {
  declare module.exports: any;
}

declare module 'all-contributors-cli/dist/util/index' {
  declare module.exports: any;
}

declare module 'all-contributors-cli/dist/util/markdown' {
  declare module.exports: any;
}

// Filename aliases
declare module 'all-contributors-cli/dist/cli.js' {
  declare module.exports: $Exports<'all-contributors-cli/dist/cli'>;
}
declare module 'all-contributors-cli/dist/contributors/add.js' {
  declare module.exports: $Exports<'all-contributors-cli/dist/contributors/add'>;
}
declare module 'all-contributors-cli/dist/contributors/index.js' {
  declare module.exports: $Exports<'all-contributors-cli/dist/contributors/index'>;
}
declare module 'all-contributors-cli/dist/contributors/prompt.js' {
  declare module.exports: $Exports<'all-contributors-cli/dist/contributors/prompt'>;
}
declare module 'all-contributors-cli/dist/generate/format-badge.js' {
  declare module.exports: $Exports<'all-contributors-cli/dist/generate/format-badge'>;
}
declare module 'all-contributors-cli/dist/generate/format-contribution-type.js' {
  declare module.exports: $Exports<'all-contributors-cli/dist/generate/format-contribution-type'>;
}
declare module 'all-contributors-cli/dist/generate/format-contributor.js' {
  declare module.exports: $Exports<'all-contributors-cli/dist/generate/format-contributor'>;
}
declare module 'all-contributors-cli/dist/generate/index.js' {
  declare module.exports: $Exports<'all-contributors-cli/dist/generate/index'>;
}
declare module 'all-contributors-cli/dist/init/index.js' {
  declare module.exports: $Exports<'all-contributors-cli/dist/init/index'>;
}
declare module 'all-contributors-cli/dist/init/init-content.js' {
  declare module.exports: $Exports<'all-contributors-cli/dist/init/init-content'>;
}
declare module 'all-contributors-cli/dist/init/prompt.js' {
  declare module.exports: $Exports<'all-contributors-cli/dist/init/prompt'>;
}
declare module 'all-contributors-cli/dist/repo/github.js' {
  declare module.exports: $Exports<'all-contributors-cli/dist/repo/github'>;
}
declare module 'all-contributors-cli/dist/repo/gitlab.js' {
  declare module.exports: $Exports<'all-contributors-cli/dist/repo/gitlab'>;
}
declare module 'all-contributors-cli/dist/repo/index.js' {
  declare module.exports: $Exports<'all-contributors-cli/dist/repo/index'>;
}
declare module 'all-contributors-cli/dist/util/config-file.js' {
  declare module.exports: $Exports<'all-contributors-cli/dist/util/config-file'>;
}
declare module 'all-contributors-cli/dist/util/contribution-types.js' {
  declare module.exports: $Exports<'all-contributors-cli/dist/util/contribution-types'>;
}
declare module 'all-contributors-cli/dist/util/git.js' {
  declare module.exports: $Exports<'all-contributors-cli/dist/util/git'>;
}
declare module 'all-contributors-cli/dist/util/index.js' {
  declare module.exports: $Exports<'all-contributors-cli/dist/util/index'>;
}
declare module 'all-contributors-cli/dist/util/markdown.js' {
  declare module.exports: $Exports<'all-contributors-cli/dist/util/markdown'>;
}
