// flow-typed signature: 4771115cc4987e26f36fd3c5779b2b58
// flow-typed version: <<STUB>>/cli-table_v^0.3.1/flow_v0.53.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'cli-table'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'cli-table' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'cli-table/lib/index' {
  declare module.exports: any;
}

declare module 'cli-table/lib/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'cli-table/lib/index.js' {
  declare module.exports: $Exports<'cli-table/lib/index'>;
}
declare module 'cli-table/lib/utils.js' {
  declare module.exports: $Exports<'cli-table/lib/utils'>;
}
