// flow-typed signature: f38c1551f7646031971bf4dfce9dfea6
// flow-typed version: <<STUB>>/commitlint_v^7.5.2/flow_v0.93.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'commitlint'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'commitlint' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'commitlint/cli' {
  declare module.exports: any;
}

// Filename aliases
declare module 'commitlint/cli.js' {
  declare module.exports: $Exports<'commitlint/cli'>;
}
