// flow-typed signature: 20d9929d3d06023c264e6d422129068a
// flow-typed version: <<STUB>>/cosmiconfig_v^5.1.0/flow_v0.93.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'cosmiconfig'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'cosmiconfig' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'cosmiconfig/dist/cacheWrapper' {
  declare module.exports: any;
}

declare module 'cosmiconfig/dist/createExplorer' {
  declare module.exports: any;
}

declare module 'cosmiconfig/dist/getDirectory' {
  declare module.exports: any;
}

declare module 'cosmiconfig/dist/index' {
  declare module.exports: any;
}

declare module 'cosmiconfig/dist/loaders' {
  declare module.exports: any;
}

declare module 'cosmiconfig/dist/readFile' {
  declare module.exports: any;
}

// Filename aliases
declare module 'cosmiconfig/dist/cacheWrapper.js' {
  declare module.exports: $Exports<'cosmiconfig/dist/cacheWrapper'>;
}
declare module 'cosmiconfig/dist/createExplorer.js' {
  declare module.exports: $Exports<'cosmiconfig/dist/createExplorer'>;
}
declare module 'cosmiconfig/dist/getDirectory.js' {
  declare module.exports: $Exports<'cosmiconfig/dist/getDirectory'>;
}
declare module 'cosmiconfig/dist/index.js' {
  declare module.exports: $Exports<'cosmiconfig/dist/index'>;
}
declare module 'cosmiconfig/dist/loaders.js' {
  declare module.exports: $Exports<'cosmiconfig/dist/loaders'>;
}
declare module 'cosmiconfig/dist/readFile.js' {
  declare module.exports: $Exports<'cosmiconfig/dist/readFile'>;
}
