// flow-typed signature: d0a6eda87e02431b03fa85a2e92435d2
// flow-typed version: <<STUB>>/cssom_v^0.3.2/flow_v0.53.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'cssom'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'cssom' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'cssom/lib/clone' {
  declare module.exports: any;
}

declare module 'cssom/lib/CSSDocumentRule' {
  declare module.exports: any;
}

declare module 'cssom/lib/CSSFontFaceRule' {
  declare module.exports: any;
}

declare module 'cssom/lib/CSSHostRule' {
  declare module.exports: any;
}

declare module 'cssom/lib/CSSImportRule' {
  declare module.exports: any;
}

declare module 'cssom/lib/CSSKeyframeRule' {
  declare module.exports: any;
}

declare module 'cssom/lib/CSSKeyframesRule' {
  declare module.exports: any;
}

declare module 'cssom/lib/CSSMediaRule' {
  declare module.exports: any;
}

declare module 'cssom/lib/CSSOM' {
  declare module.exports: any;
}

declare module 'cssom/lib/CSSRule' {
  declare module.exports: any;
}

declare module 'cssom/lib/CSSStyleDeclaration' {
  declare module.exports: any;
}

declare module 'cssom/lib/CSSStyleRule' {
  declare module.exports: any;
}

declare module 'cssom/lib/CSSStyleSheet' {
  declare module.exports: any;
}

declare module 'cssom/lib/CSSValue' {
  declare module.exports: any;
}

declare module 'cssom/lib/CSSValueExpression' {
  declare module.exports: any;
}

declare module 'cssom/lib/index' {
  declare module.exports: any;
}

declare module 'cssom/lib/MatcherList' {
  declare module.exports: any;
}

declare module 'cssom/lib/MediaList' {
  declare module.exports: any;
}

declare module 'cssom/lib/parse' {
  declare module.exports: any;
}

declare module 'cssom/lib/Parser' {
  declare module.exports: any;
}

declare module 'cssom/lib/snapshot' {
  declare module.exports: any;
}

declare module 'cssom/lib/StyleSheet' {
  declare module.exports: any;
}

// Filename aliases
declare module 'cssom/lib/clone.js' {
  declare module.exports: $Exports<'cssom/lib/clone'>;
}
declare module 'cssom/lib/CSSDocumentRule.js' {
  declare module.exports: $Exports<'cssom/lib/CSSDocumentRule'>;
}
declare module 'cssom/lib/CSSFontFaceRule.js' {
  declare module.exports: $Exports<'cssom/lib/CSSFontFaceRule'>;
}
declare module 'cssom/lib/CSSHostRule.js' {
  declare module.exports: $Exports<'cssom/lib/CSSHostRule'>;
}
declare module 'cssom/lib/CSSImportRule.js' {
  declare module.exports: $Exports<'cssom/lib/CSSImportRule'>;
}
declare module 'cssom/lib/CSSKeyframeRule.js' {
  declare module.exports: $Exports<'cssom/lib/CSSKeyframeRule'>;
}
declare module 'cssom/lib/CSSKeyframesRule.js' {
  declare module.exports: $Exports<'cssom/lib/CSSKeyframesRule'>;
}
declare module 'cssom/lib/CSSMediaRule.js' {
  declare module.exports: $Exports<'cssom/lib/CSSMediaRule'>;
}
declare module 'cssom/lib/CSSOM.js' {
  declare module.exports: $Exports<'cssom/lib/CSSOM'>;
}
declare module 'cssom/lib/CSSRule.js' {
  declare module.exports: $Exports<'cssom/lib/CSSRule'>;
}
declare module 'cssom/lib/CSSStyleDeclaration.js' {
  declare module.exports: $Exports<'cssom/lib/CSSStyleDeclaration'>;
}
declare module 'cssom/lib/CSSStyleRule.js' {
  declare module.exports: $Exports<'cssom/lib/CSSStyleRule'>;
}
declare module 'cssom/lib/CSSStyleSheet.js' {
  declare module.exports: $Exports<'cssom/lib/CSSStyleSheet'>;
}
declare module 'cssom/lib/CSSValue.js' {
  declare module.exports: $Exports<'cssom/lib/CSSValue'>;
}
declare module 'cssom/lib/CSSValueExpression.js' {
  declare module.exports: $Exports<'cssom/lib/CSSValueExpression'>;
}
declare module 'cssom/lib/index.js' {
  declare module.exports: $Exports<'cssom/lib/index'>;
}
declare module 'cssom/lib/MatcherList.js' {
  declare module.exports: $Exports<'cssom/lib/MatcherList'>;
}
declare module 'cssom/lib/MediaList.js' {
  declare module.exports: $Exports<'cssom/lib/MediaList'>;
}
declare module 'cssom/lib/parse.js' {
  declare module.exports: $Exports<'cssom/lib/parse'>;
}
declare module 'cssom/lib/Parser.js' {
  declare module.exports: $Exports<'cssom/lib/Parser'>;
}
declare module 'cssom/lib/snapshot.js' {
  declare module.exports: $Exports<'cssom/lib/snapshot'>;
}
declare module 'cssom/lib/StyleSheet.js' {
  declare module.exports: $Exports<'cssom/lib/StyleSheet'>;
}
