// flow-typed signature: 927a6714eaf0d6f5c001f9d54c44e987
// flow-typed version: <<STUB>>/dedent_v^0.7.0/flow_v0.52.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'dedent'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'dedent' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'dedent/dist/dedent' {
  declare module.exports: any;
}

// Filename aliases
declare module 'dedent/dist/dedent.js' {
  declare module.exports: $Exports<'dedent/dist/dedent'>;
}
