// flow-typed signature: 3234edde202cdc99b71d849f0b259144
// flow-typed version: <<STUB>>/dtslint_v^0.4.9/flow_v0.93.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'dtslint'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'dtslint' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'dtslint/bin/checks' {
  declare module.exports: any;
}

declare module 'dtslint/bin/index' {
  declare module.exports: any;
}

declare module 'dtslint/bin/installer' {
  declare module.exports: any;
}

declare module 'dtslint/bin/lint' {
  declare module.exports: any;
}

declare module 'dtslint/bin/rules/dtHeaderRule' {
  declare module.exports: any;
}

declare module 'dtslint/bin/rules/expectRule' {
  declare module.exports: any;
}

declare module 'dtslint/bin/rules/exportJustNamespaceRule' {
  declare module.exports: any;
}

declare module 'dtslint/bin/rules/noAnyUnionRule' {
  declare module.exports: any;
}

declare module 'dtslint/bin/rules/noBadReferenceRule' {
  declare module.exports: any;
}

declare module 'dtslint/bin/rules/noConstEnumRule' {
  declare module.exports: any;
}

declare module 'dtslint/bin/rules/noDeadReferenceRule' {
  declare module.exports: any;
}

declare module 'dtslint/bin/rules/noDeclareCurrentPackageRule' {
  declare module.exports: any;
}

declare module 'dtslint/bin/rules/noImportDefaultOfExportEqualsRule' {
  declare module.exports: any;
}

declare module 'dtslint/bin/rules/noOutsideDependenciesRule' {
  declare module.exports: any;
}

declare module 'dtslint/bin/rules/noPaddingRule' {
  declare module.exports: any;
}

declare module 'dtslint/bin/rules/noRedundantJsdoc2Rule' {
  declare module.exports: any;
}

declare module 'dtslint/bin/rules/noRedundantUndefinedRule' {
  declare module.exports: any;
}

declare module 'dtslint/bin/rules/noRelativeImportInTestRule' {
  declare module.exports: any;
}

declare module 'dtslint/bin/rules/noSelfImportRule' {
  declare module.exports: any;
}

declare module 'dtslint/bin/rules/noSingleDeclareModuleRule' {
  declare module.exports: any;
}

declare module 'dtslint/bin/rules/noSingleElementTupleTypeRule' {
  declare module.exports: any;
}

declare module 'dtslint/bin/rules/noUnnecessaryGenericsRule' {
  declare module.exports: any;
}

declare module 'dtslint/bin/rules/noUselessFilesRule' {
  declare module.exports: any;
}

declare module 'dtslint/bin/rules/preferDeclareFunctionRule' {
  declare module.exports: any;
}

declare module 'dtslint/bin/rules/strictExportDeclareModifiersRule' {
  declare module.exports: any;
}

declare module 'dtslint/bin/rules/trimFileRule' {
  declare module.exports: any;
}

declare module 'dtslint/bin/rules/voidReturnRule' {
  declare module.exports: any;
}

declare module 'dtslint/bin/util' {
  declare module.exports: any;
}

// Filename aliases
declare module 'dtslint/bin/checks.js' {
  declare module.exports: $Exports<'dtslint/bin/checks'>;
}
declare module 'dtslint/bin/index.js' {
  declare module.exports: $Exports<'dtslint/bin/index'>;
}
declare module 'dtslint/bin/installer.js' {
  declare module.exports: $Exports<'dtslint/bin/installer'>;
}
declare module 'dtslint/bin/lint.js' {
  declare module.exports: $Exports<'dtslint/bin/lint'>;
}
declare module 'dtslint/bin/rules/dtHeaderRule.js' {
  declare module.exports: $Exports<'dtslint/bin/rules/dtHeaderRule'>;
}
declare module 'dtslint/bin/rules/expectRule.js' {
  declare module.exports: $Exports<'dtslint/bin/rules/expectRule'>;
}
declare module 'dtslint/bin/rules/exportJustNamespaceRule.js' {
  declare module.exports: $Exports<'dtslint/bin/rules/exportJustNamespaceRule'>;
}
declare module 'dtslint/bin/rules/noAnyUnionRule.js' {
  declare module.exports: $Exports<'dtslint/bin/rules/noAnyUnionRule'>;
}
declare module 'dtslint/bin/rules/noBadReferenceRule.js' {
  declare module.exports: $Exports<'dtslint/bin/rules/noBadReferenceRule'>;
}
declare module 'dtslint/bin/rules/noConstEnumRule.js' {
  declare module.exports: $Exports<'dtslint/bin/rules/noConstEnumRule'>;
}
declare module 'dtslint/bin/rules/noDeadReferenceRule.js' {
  declare module.exports: $Exports<'dtslint/bin/rules/noDeadReferenceRule'>;
}
declare module 'dtslint/bin/rules/noDeclareCurrentPackageRule.js' {
  declare module.exports: $Exports<'dtslint/bin/rules/noDeclareCurrentPackageRule'>;
}
declare module 'dtslint/bin/rules/noImportDefaultOfExportEqualsRule.js' {
  declare module.exports: $Exports<'dtslint/bin/rules/noImportDefaultOfExportEqualsRule'>;
}
declare module 'dtslint/bin/rules/noOutsideDependenciesRule.js' {
  declare module.exports: $Exports<'dtslint/bin/rules/noOutsideDependenciesRule'>;
}
declare module 'dtslint/bin/rules/noPaddingRule.js' {
  declare module.exports: $Exports<'dtslint/bin/rules/noPaddingRule'>;
}
declare module 'dtslint/bin/rules/noRedundantJsdoc2Rule.js' {
  declare module.exports: $Exports<'dtslint/bin/rules/noRedundantJsdoc2Rule'>;
}
declare module 'dtslint/bin/rules/noRedundantUndefinedRule.js' {
  declare module.exports: $Exports<'dtslint/bin/rules/noRedundantUndefinedRule'>;
}
declare module 'dtslint/bin/rules/noRelativeImportInTestRule.js' {
  declare module.exports: $Exports<'dtslint/bin/rules/noRelativeImportInTestRule'>;
}
declare module 'dtslint/bin/rules/noSelfImportRule.js' {
  declare module.exports: $Exports<'dtslint/bin/rules/noSelfImportRule'>;
}
declare module 'dtslint/bin/rules/noSingleDeclareModuleRule.js' {
  declare module.exports: $Exports<'dtslint/bin/rules/noSingleDeclareModuleRule'>;
}
declare module 'dtslint/bin/rules/noSingleElementTupleTypeRule.js' {
  declare module.exports: $Exports<'dtslint/bin/rules/noSingleElementTupleTypeRule'>;
}
declare module 'dtslint/bin/rules/noUnnecessaryGenericsRule.js' {
  declare module.exports: $Exports<'dtslint/bin/rules/noUnnecessaryGenericsRule'>;
}
declare module 'dtslint/bin/rules/noUselessFilesRule.js' {
  declare module.exports: $Exports<'dtslint/bin/rules/noUselessFilesRule'>;
}
declare module 'dtslint/bin/rules/preferDeclareFunctionRule.js' {
  declare module.exports: $Exports<'dtslint/bin/rules/preferDeclareFunctionRule'>;
}
declare module 'dtslint/bin/rules/strictExportDeclareModifiersRule.js' {
  declare module.exports: $Exports<'dtslint/bin/rules/strictExportDeclareModifiersRule'>;
}
declare module 'dtslint/bin/rules/trimFileRule.js' {
  declare module.exports: $Exports<'dtslint/bin/rules/trimFileRule'>;
}
declare module 'dtslint/bin/rules/voidReturnRule.js' {
  declare module.exports: $Exports<'dtslint/bin/rules/voidReturnRule'>;
}
declare module 'dtslint/bin/util.js' {
  declare module.exports: $Exports<'dtslint/bin/util'>;
}
