// flow-typed signature: c79cd4ab1fb578a56e26fb057e479912
// flow-typed version: <<STUB>>/enhanced-resolve_v^4.1.0/flow_v0.93.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'enhanced-resolve'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'enhanced-resolve' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'enhanced-resolve/lib/AliasFieldPlugin' {
  declare module.exports: any;
}

declare module 'enhanced-resolve/lib/AliasPlugin' {
  declare module.exports: any;
}

declare module 'enhanced-resolve/lib/AppendPlugin' {
  declare module.exports: any;
}

declare module 'enhanced-resolve/lib/CachedInputFileSystem' {
  declare module.exports: any;
}

declare module 'enhanced-resolve/lib/CloneBasenamePlugin' {
  declare module.exports: any;
}

declare module 'enhanced-resolve/lib/concord' {
  declare module.exports: any;
}

declare module 'enhanced-resolve/lib/ConcordExtensionsPlugin' {
  declare module.exports: any;
}

declare module 'enhanced-resolve/lib/ConcordMainPlugin' {
  declare module.exports: any;
}

declare module 'enhanced-resolve/lib/ConcordModulesPlugin' {
  declare module.exports: any;
}

declare module 'enhanced-resolve/lib/createInnerCallback' {
  declare module.exports: any;
}

declare module 'enhanced-resolve/lib/createInnerContext' {
  declare module.exports: any;
}

declare module 'enhanced-resolve/lib/DescriptionFilePlugin' {
  declare module.exports: any;
}

declare module 'enhanced-resolve/lib/DescriptionFileUtils' {
  declare module.exports: any;
}

declare module 'enhanced-resolve/lib/DirectoryExistsPlugin' {
  declare module.exports: any;
}

declare module 'enhanced-resolve/lib/FileExistsPlugin' {
  declare module.exports: any;
}

declare module 'enhanced-resolve/lib/FileKindPlugin' {
  declare module.exports: any;
}

declare module 'enhanced-resolve/lib/forEachBail' {
  declare module.exports: any;
}

declare module 'enhanced-resolve/lib/getInnerRequest' {
  declare module.exports: any;
}

declare module 'enhanced-resolve/lib/getPaths' {
  declare module.exports: any;
}

declare module 'enhanced-resolve/lib/globToRegExp' {
  declare module.exports: any;
}

declare module 'enhanced-resolve/lib/JoinRequestPlugin' {
  declare module.exports: any;
}

declare module 'enhanced-resolve/lib/LogInfoPlugin' {
  declare module.exports: any;
}

declare module 'enhanced-resolve/lib/MainFieldPlugin' {
  declare module.exports: any;
}

declare module 'enhanced-resolve/lib/ModuleAppendPlugin' {
  declare module.exports: any;
}

declare module 'enhanced-resolve/lib/ModuleKindPlugin' {
  declare module.exports: any;
}

declare module 'enhanced-resolve/lib/ModulesInHierachicDirectoriesPlugin' {
  declare module.exports: any;
}

declare module 'enhanced-resolve/lib/ModulesInRootPlugin' {
  declare module.exports: any;
}

declare module 'enhanced-resolve/lib/NextPlugin' {
  declare module.exports: any;
}

declare module 'enhanced-resolve/lib/node' {
  declare module.exports: any;
}

declare module 'enhanced-resolve/lib/NodeJsInputFileSystem' {
  declare module.exports: any;
}

declare module 'enhanced-resolve/lib/ParsePlugin' {
  declare module.exports: any;
}

declare module 'enhanced-resolve/lib/Resolver' {
  declare module.exports: any;
}

declare module 'enhanced-resolve/lib/ResolverFactory' {
  declare module.exports: any;
}

declare module 'enhanced-resolve/lib/ResultPlugin' {
  declare module.exports: any;
}

declare module 'enhanced-resolve/lib/SymlinkPlugin' {
  declare module.exports: any;
}

declare module 'enhanced-resolve/lib/SyncAsyncFileSystemDecorator' {
  declare module.exports: any;
}

declare module 'enhanced-resolve/lib/TryNextPlugin' {
  declare module.exports: any;
}

declare module 'enhanced-resolve/lib/UnsafeCachePlugin' {
  declare module.exports: any;
}

declare module 'enhanced-resolve/lib/UseFilePlugin' {
  declare module.exports: any;
}

// Filename aliases
declare module 'enhanced-resolve/lib/AliasFieldPlugin.js' {
  declare module.exports: $Exports<'enhanced-resolve/lib/AliasFieldPlugin'>;
}
declare module 'enhanced-resolve/lib/AliasPlugin.js' {
  declare module.exports: $Exports<'enhanced-resolve/lib/AliasPlugin'>;
}
declare module 'enhanced-resolve/lib/AppendPlugin.js' {
  declare module.exports: $Exports<'enhanced-resolve/lib/AppendPlugin'>;
}
declare module 'enhanced-resolve/lib/CachedInputFileSystem.js' {
  declare module.exports: $Exports<'enhanced-resolve/lib/CachedInputFileSystem'>;
}
declare module 'enhanced-resolve/lib/CloneBasenamePlugin.js' {
  declare module.exports: $Exports<'enhanced-resolve/lib/CloneBasenamePlugin'>;
}
declare module 'enhanced-resolve/lib/concord.js' {
  declare module.exports: $Exports<'enhanced-resolve/lib/concord'>;
}
declare module 'enhanced-resolve/lib/ConcordExtensionsPlugin.js' {
  declare module.exports: $Exports<'enhanced-resolve/lib/ConcordExtensionsPlugin'>;
}
declare module 'enhanced-resolve/lib/ConcordMainPlugin.js' {
  declare module.exports: $Exports<'enhanced-resolve/lib/ConcordMainPlugin'>;
}
declare module 'enhanced-resolve/lib/ConcordModulesPlugin.js' {
  declare module.exports: $Exports<'enhanced-resolve/lib/ConcordModulesPlugin'>;
}
declare module 'enhanced-resolve/lib/createInnerCallback.js' {
  declare module.exports: $Exports<'enhanced-resolve/lib/createInnerCallback'>;
}
declare module 'enhanced-resolve/lib/createInnerContext.js' {
  declare module.exports: $Exports<'enhanced-resolve/lib/createInnerContext'>;
}
declare module 'enhanced-resolve/lib/DescriptionFilePlugin.js' {
  declare module.exports: $Exports<'enhanced-resolve/lib/DescriptionFilePlugin'>;
}
declare module 'enhanced-resolve/lib/DescriptionFileUtils.js' {
  declare module.exports: $Exports<'enhanced-resolve/lib/DescriptionFileUtils'>;
}
declare module 'enhanced-resolve/lib/DirectoryExistsPlugin.js' {
  declare module.exports: $Exports<'enhanced-resolve/lib/DirectoryExistsPlugin'>;
}
declare module 'enhanced-resolve/lib/FileExistsPlugin.js' {
  declare module.exports: $Exports<'enhanced-resolve/lib/FileExistsPlugin'>;
}
declare module 'enhanced-resolve/lib/FileKindPlugin.js' {
  declare module.exports: $Exports<'enhanced-resolve/lib/FileKindPlugin'>;
}
declare module 'enhanced-resolve/lib/forEachBail.js' {
  declare module.exports: $Exports<'enhanced-resolve/lib/forEachBail'>;
}
declare module 'enhanced-resolve/lib/getInnerRequest.js' {
  declare module.exports: $Exports<'enhanced-resolve/lib/getInnerRequest'>;
}
declare module 'enhanced-resolve/lib/getPaths.js' {
  declare module.exports: $Exports<'enhanced-resolve/lib/getPaths'>;
}
declare module 'enhanced-resolve/lib/globToRegExp.js' {
  declare module.exports: $Exports<'enhanced-resolve/lib/globToRegExp'>;
}
declare module 'enhanced-resolve/lib/JoinRequestPlugin.js' {
  declare module.exports: $Exports<'enhanced-resolve/lib/JoinRequestPlugin'>;
}
declare module 'enhanced-resolve/lib/LogInfoPlugin.js' {
  declare module.exports: $Exports<'enhanced-resolve/lib/LogInfoPlugin'>;
}
declare module 'enhanced-resolve/lib/MainFieldPlugin.js' {
  declare module.exports: $Exports<'enhanced-resolve/lib/MainFieldPlugin'>;
}
declare module 'enhanced-resolve/lib/ModuleAppendPlugin.js' {
  declare module.exports: $Exports<'enhanced-resolve/lib/ModuleAppendPlugin'>;
}
declare module 'enhanced-resolve/lib/ModuleKindPlugin.js' {
  declare module.exports: $Exports<'enhanced-resolve/lib/ModuleKindPlugin'>;
}
declare module 'enhanced-resolve/lib/ModulesInHierachicDirectoriesPlugin.js' {
  declare module.exports: $Exports<'enhanced-resolve/lib/ModulesInHierachicDirectoriesPlugin'>;
}
declare module 'enhanced-resolve/lib/ModulesInRootPlugin.js' {
  declare module.exports: $Exports<'enhanced-resolve/lib/ModulesInRootPlugin'>;
}
declare module 'enhanced-resolve/lib/NextPlugin.js' {
  declare module.exports: $Exports<'enhanced-resolve/lib/NextPlugin'>;
}
declare module 'enhanced-resolve/lib/node.js' {
  declare module.exports: $Exports<'enhanced-resolve/lib/node'>;
}
declare module 'enhanced-resolve/lib/NodeJsInputFileSystem.js' {
  declare module.exports: $Exports<'enhanced-resolve/lib/NodeJsInputFileSystem'>;
}
declare module 'enhanced-resolve/lib/ParsePlugin.js' {
  declare module.exports: $Exports<'enhanced-resolve/lib/ParsePlugin'>;
}
declare module 'enhanced-resolve/lib/Resolver.js' {
  declare module.exports: $Exports<'enhanced-resolve/lib/Resolver'>;
}
declare module 'enhanced-resolve/lib/ResolverFactory.js' {
  declare module.exports: $Exports<'enhanced-resolve/lib/ResolverFactory'>;
}
declare module 'enhanced-resolve/lib/ResultPlugin.js' {
  declare module.exports: $Exports<'enhanced-resolve/lib/ResultPlugin'>;
}
declare module 'enhanced-resolve/lib/SymlinkPlugin.js' {
  declare module.exports: $Exports<'enhanced-resolve/lib/SymlinkPlugin'>;
}
declare module 'enhanced-resolve/lib/SyncAsyncFileSystemDecorator.js' {
  declare module.exports: $Exports<'enhanced-resolve/lib/SyncAsyncFileSystemDecorator'>;
}
declare module 'enhanced-resolve/lib/TryNextPlugin.js' {
  declare module.exports: $Exports<'enhanced-resolve/lib/TryNextPlugin'>;
}
declare module 'enhanced-resolve/lib/UnsafeCachePlugin.js' {
  declare module.exports: $Exports<'enhanced-resolve/lib/UnsafeCachePlugin'>;
}
declare module 'enhanced-resolve/lib/UseFilePlugin.js' {
  declare module.exports: $Exports<'enhanced-resolve/lib/UseFilePlugin'>;
}
