// flow-typed signature: 0e81e34bd1baf8452aa5d8ba3ba7aea5
// flow-typed version: <<STUB>>/error-stack-parser_v^2.0.1/flow_v0.53.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'error-stack-parser'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'error-stack-parser' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'error-stack-parser/dist/error-stack-parser' {
  declare module.exports: any;
}

declare module 'error-stack-parser/dist/error-stack-parser.min' {
  declare module.exports: any;
}

declare module 'error-stack-parser/error-stack-parser' {
  declare module.exports: any;
}

// Filename aliases
declare module 'error-stack-parser/dist/error-stack-parser.js' {
  declare module.exports: $Exports<'error-stack-parser/dist/error-stack-parser'>;
}
declare module 'error-stack-parser/dist/error-stack-parser.min.js' {
  declare module.exports: $Exports<'error-stack-parser/dist/error-stack-parser.min'>;
}
declare module 'error-stack-parser/error-stack-parser.js' {
  declare module.exports: $Exports<'error-stack-parser/error-stack-parser'>;
}
