// flow-typed signature: 7e521d5acdbfc59890e478056186910e
// flow-typed version: <<STUB>>/release-it_v^10.1.0/flow_v0.93.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'release-it'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'release-it' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'release-it/bin/release-it' {
  declare module.exports: any;
}

declare module 'release-it/lib/changelog' {
  declare module.exports: any;
}

declare module 'release-it/lib/cli' {
  declare module.exports: any;
}

declare module 'release-it/lib/config' {
  declare module.exports: any;
}

declare module 'release-it/lib/deprecated' {
  declare module.exports: any;
}

declare module 'release-it/lib/errors' {
  declare module.exports: any;
}

declare module 'release-it/lib/git' {
  declare module.exports: any;
}

declare module 'release-it/lib/github' {
  declare module.exports: any;
}

declare module 'release-it/lib/gitlab' {
  declare module.exports: any;
}

declare module 'release-it/lib/index' {
  declare module.exports: any;
}

declare module 'release-it/lib/log' {
  declare module.exports: any;
}

declare module 'release-it/lib/metrics' {
  declare module.exports: any;
}

declare module 'release-it/lib/npm' {
  declare module.exports: any;
}

declare module 'release-it/lib/prompt' {
  declare module.exports: any;
}

declare module 'release-it/lib/recommendations' {
  declare module.exports: any;
}

declare module 'release-it/lib/release' {
  declare module.exports: any;
}

declare module 'release-it/lib/shell' {
  declare module.exports: any;
}

declare module 'release-it/lib/spinner' {
  declare module.exports: any;
}

declare module 'release-it/lib/tasks' {
  declare module.exports: any;
}

declare module 'release-it/lib/util' {
  declare module.exports: any;
}

declare module 'release-it/lib/version' {
  declare module.exports: any;
}

// Filename aliases
declare module 'release-it/bin/release-it.js' {
  declare module.exports: $Exports<'release-it/bin/release-it'>;
}
declare module 'release-it/lib/changelog.js' {
  declare module.exports: $Exports<'release-it/lib/changelog'>;
}
declare module 'release-it/lib/cli.js' {
  declare module.exports: $Exports<'release-it/lib/cli'>;
}
declare module 'release-it/lib/config.js' {
  declare module.exports: $Exports<'release-it/lib/config'>;
}
declare module 'release-it/lib/deprecated.js' {
  declare module.exports: $Exports<'release-it/lib/deprecated'>;
}
declare module 'release-it/lib/errors.js' {
  declare module.exports: $Exports<'release-it/lib/errors'>;
}
declare module 'release-it/lib/git.js' {
  declare module.exports: $Exports<'release-it/lib/git'>;
}
declare module 'release-it/lib/github.js' {
  declare module.exports: $Exports<'release-it/lib/github'>;
}
declare module 'release-it/lib/gitlab.js' {
  declare module.exports: $Exports<'release-it/lib/gitlab'>;
}
declare module 'release-it/lib/index.js' {
  declare module.exports: $Exports<'release-it/lib/index'>;
}
declare module 'release-it/lib/log.js' {
  declare module.exports: $Exports<'release-it/lib/log'>;
}
declare module 'release-it/lib/metrics.js' {
  declare module.exports: $Exports<'release-it/lib/metrics'>;
}
declare module 'release-it/lib/npm.js' {
  declare module.exports: $Exports<'release-it/lib/npm'>;
}
declare module 'release-it/lib/prompt.js' {
  declare module.exports: $Exports<'release-it/lib/prompt'>;
}
declare module 'release-it/lib/recommendations.js' {
  declare module.exports: $Exports<'release-it/lib/recommendations'>;
}
declare module 'release-it/lib/release.js' {
  declare module.exports: $Exports<'release-it/lib/release'>;
}
declare module 'release-it/lib/shell.js' {
  declare module.exports: $Exports<'release-it/lib/shell'>;
}
declare module 'release-it/lib/spinner.js' {
  declare module.exports: $Exports<'release-it/lib/spinner'>;
}
declare module 'release-it/lib/tasks.js' {
  declare module.exports: $Exports<'release-it/lib/tasks'>;
}
declare module 'release-it/lib/util.js' {
  declare module.exports: $Exports<'release-it/lib/util'>;
}
declare module 'release-it/lib/version.js' {
  declare module.exports: $Exports<'release-it/lib/version'>;
}
