// flow-typed signature: cf44826628457b3189cfd54c649d8a6c
// flow-typed version: <<STUB>>/rollup-pluginutils_v^2.3.3/flow_v0.83.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'rollup-pluginutils'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'rollup-pluginutils' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'rollup-pluginutils/dist/pluginutils.cjs' {
  declare module.exports: any;
}

declare module 'rollup-pluginutils/dist/pluginutils.es' {
  declare module.exports: any;
}

declare module 'rollup-pluginutils/src/addExtension' {
  declare module.exports: any;
}

declare module 'rollup-pluginutils/src/attachScopes' {
  declare module.exports: any;
}

declare module 'rollup-pluginutils/src/createFilter' {
  declare module.exports: any;
}

declare module 'rollup-pluginutils/src/dataToEsm' {
  declare module.exports: any;
}

declare module 'rollup-pluginutils/src/index' {
  declare module.exports: any;
}

declare module 'rollup-pluginutils/src/makeLegalIdentifier' {
  declare module.exports: any;
}

declare module 'rollup-pluginutils/src/utils/ensureArray' {
  declare module.exports: any;
}

// Filename aliases
declare module 'rollup-pluginutils/dist/pluginutils.cjs.js' {
  declare module.exports: $Exports<'rollup-pluginutils/dist/pluginutils.cjs'>;
}
declare module 'rollup-pluginutils/dist/pluginutils.es.js' {
  declare module.exports: $Exports<'rollup-pluginutils/dist/pluginutils.es'>;
}
declare module 'rollup-pluginutils/src/addExtension.js' {
  declare module.exports: $Exports<'rollup-pluginutils/src/addExtension'>;
}
declare module 'rollup-pluginutils/src/attachScopes.js' {
  declare module.exports: $Exports<'rollup-pluginutils/src/attachScopes'>;
}
declare module 'rollup-pluginutils/src/createFilter.js' {
  declare module.exports: $Exports<'rollup-pluginutils/src/createFilter'>;
}
declare module 'rollup-pluginutils/src/dataToEsm.js' {
  declare module.exports: $Exports<'rollup-pluginutils/src/dataToEsm'>;
}
declare module 'rollup-pluginutils/src/index.js' {
  declare module.exports: $Exports<'rollup-pluginutils/src/index'>;
}
declare module 'rollup-pluginutils/src/makeLegalIdentifier.js' {
  declare module.exports: $Exports<'rollup-pluginutils/src/makeLegalIdentifier'>;
}
declare module 'rollup-pluginutils/src/utils/ensureArray.js' {
  declare module.exports: $Exports<'rollup-pluginutils/src/utils/ensureArray'>;
}
