// flow-typed signature: e5a1b6b4e84e5adac41f3b3468718325
// flow-typed version: <<STUB>>/rollup-pluginutils_v^2.4.1/flow_v0.93.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'rollup-pluginutils'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'rollup-pluginutils' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'rollup-pluginutils/dist/pluginutils.cjs' {
  declare module.exports: any;
}

declare module 'rollup-pluginutils/dist/pluginutils.es' {
  declare module.exports: any;
}

// Filename aliases
declare module 'rollup-pluginutils/dist/pluginutils.cjs.js' {
  declare module.exports: $Exports<'rollup-pluginutils/dist/pluginutils.cjs'>;
}
declare module 'rollup-pluginutils/dist/pluginutils.es.js' {
  declare module.exports: $Exports<'rollup-pluginutils/dist/pluginutils.es'>;
}
