// flow-typed signature: e92c45f62f09260954266a7395154f20
// flow-typed version: <<STUB>>/short-hash_v^1.0.0/flow_v0.52.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'short-hash'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'short-hash' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'short-hash/src/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'short-hash/src/index.js' {
  declare module.exports: $Exports<'short-hash/src/index'>;
}
