// flow-typed signature: 7ddb6e2fed5478e9f4c633fdaf54ac77
// flow-typed version: <<STUB>>/@babel/plugin-syntax-dynamic-import_v^7.0.0/flow_v0.83.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@babel/plugin-syntax-dynamic-import'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@babel/plugin-syntax-dynamic-import' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@babel/plugin-syntax-dynamic-import/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module '@babel/plugin-syntax-dynamic-import/lib/index.js' {
  declare module.exports: $Exports<'@babel/plugin-syntax-dynamic-import/lib/index'>;
}
